var districthq = [{

"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Taplejung", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.6737, 27.3576 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Phidim", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.7667, 27.1467 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Chandragadhi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 88.0661, 26.5695 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Biratnagar", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.2791, 26.4565 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Inaruwa", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.1489, 26.6018 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Terhathum", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.5370, 27.1265 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Khandbari", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.2070, 27.3780 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Bhojpur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 87.0481, 27.1722 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Salleri", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.5857, 27.5033 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Diktel", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.7927, 27.2169 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Okhaldhunga", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.5029, 27.3144 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Gaighat", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.6988, 26.7914 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Siraha", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.2072, 26.6529 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Janakpur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.9282, 26.7324 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Jaleshwar", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.7999, 26.6485 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Malangawa", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.5578, 26.8569 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Ramechhap", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.0848, 27.3224 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Charikot", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 86.0499, 27.6671 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Chautara", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.7146, 27.7752 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dhulikhel", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.5519, 27.6186 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Patan", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.3257, 27.6740 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Bhaktapur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.4262, 27.6717 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Bidur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.1425, 27.9140 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dhunche", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.2965, 28.1132 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dhading Besi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.8956, 27.9126 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Gaur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.2798, 26.7642 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Kalaiya", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 85.0042, 27.0338 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Birganj", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.8768, 27.0122 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Bharatpur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.4322, 27.6794 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Gorkha", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.6216, 27.9986 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Besi Sahar", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.3785, 28.2286 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Chame", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.2426, 28.5527 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Damauli", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 84.2678, 27.9755 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Syangja", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.8715, 28.0997 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Kushma", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.6790, 28.2201 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Beni", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.5655, 28.3439 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Jomsom", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.7310, 28.7847 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Tansen", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.5456, 27.8670 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Parasi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.6681, 27.5331 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Siddharthnagar", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.4516, 27.5067 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Taulihawa", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.0539, 27.5458 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Sandhikharka", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.1265, 27.9723 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Tamghas", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 83.2461, 28.0676 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Jumlikhalanga", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.4551, 28.6284 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Salyan", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.1631, 28.3777 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Libang", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.6361, 28.3043 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Khalanga", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.8836, 28.0896 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Ghorahi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.4866, 28.0443 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Gulariya", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.3455, 28.2065 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Jajarkot", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.1959, 28.6986 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dailekh", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.7090, 28.8376 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dunai", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.8931, 28.9539 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Manma", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.5966, 29.1442 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Gamgadhi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 82.1562, 29.5469 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Simikot", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.8223, 29.9693 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Chainpur", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.1982, 29.5531 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Martadi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.4797, 29.4580 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Mangalsen", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 81.2565, 29.1408 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Silgadhi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 80.9848, 29.2680 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dhangadhi", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 80.5908, 28.7018 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Dadeldhura", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 80.5846, 29.2996 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Patan", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 80.5482, 29.4666 ] } },
{ "type": "Feature", "properties": { "STATUS": "District Headquarter", "HQNAME": "Darchula", "RADIUS": 2 }, "geometry": { "type": "Point", "coordinates": [ 80.5399, 29.8436 ] } }
]
}
];